### ISSUE TITLE
predictor_load.add_input method not working

### ISSUE THREAD

**Issue by chetanambi** [MAIF/shapash#109]
Thanks for your wonderful work on this !! 

While exploring **tutorial03-Shapash-overview-model-in-production.ipynb** notebook I am running into below errors. 

**Issue# 1**
When executing `predictor_load.add_input(x=Xtrain, ypred=ytrain)` method. It's clear from the error message that Xtrain's dtypes are not matching with original dataset's dtypes. The features_types has dtypes before preprocessing and Xtrain is having after preprocessing dtypes. So both will never match. 
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-74-f4ec8d8babcb> in <module>
----> 1 predictor_load.add_input(x=Xtrain, ypred=ytrain)

c:\users\chetan_ambi\.conda\envs\shapash\lib\site-packages\shapash\explainer\smart_predictor.py in add_input(self, x, ypred, contributions)
    195         """
    196         if x is not None:
--> 197             x = self.check_dataset_features(self.check_dataset_type(x))
    198             self.data = self.clean_data(x)
    199             self.data["x_postprocessed"] = self.apply_postprocessing()

c:\users\chetan_ambi\.conda\envs\shapash\lib\site-packages\shapash\explainer\smart_predictor.py in check_dataset_features(self, x)
    293         assert all(column in self.features_types.keys() for column in x.columns)
    294         if not all([str(x[feature].dtypes) == self.features_types[feature] for feature in x.columns]):
--> 295             raise ValueError("Types of features in x doesn't match with the expected one in features_types.")
    296         return x
    297 

ValueError: Types of features in x doesn't match with the expected one in features_types.
```

**Issue#2**

It's considering only np.float, np.int. Should we consider adding np.int32, np.float32, np.int64, np.float64

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-24-f4ec8d8babcb> in <module>
----> 1 predictor_load.add_input(x=Xtrain, ypred=ytrain)

c:\users\chetan_ambi\.conda\envs\shapash\lib\site-packages\shapash\explainer\smart_predictor.py in add_input(self, x, ypred, contributions)
    211 
    212         if ypred is not None:
--> 213             self.data["ypred_init"] = self.check_ypred(ypred)
    214 
    215         if contributions is not None:

c:\users\chetan_ambi\.conda\envs\shapash\lib\site-packages\shapash\explainer\smart_predictor.py in check_ypred(self, ypred)
    305             User-specified prediction values.
    306         """
--> 307         return check_ypred(self.data["x"],ypred)
    308 
    309     def choose_state(self, contributions):

c:\users\chetan_ambi\.conda\envs\shapash\lib\site-packages\shapash\utils\check.py in check_ypred(x, ypred)
    135                 raise ValueError("y_pred must be a one column pd.Dataframe or pd.Series.")
    136             if not (ypred.dtypes[0] in [np.float, np.int]):
--> 137                 raise ValueError("y_pred must contain int or float only")
    138         if isinstance(ypred, pd.Series):
    139             if not (ypred.dtype in [np.float, np.int]):

ValueError: y_pred must contain int or float only
```

**Comment by johannmartin** [comment]
Hello @chetanambi,

Thanks for your comment. It will really help us to have some user's feedback on Shapash.

About issue# 1 : 
- add_input method, available with the SmartPredictor object, requires a pandas.DataFrame or dict x which corresponds to a raw dataset (before using preprocessing step in order to use your model to predict on it.). The add_input method will apply the preprocessing for you. In the example of the tutorial, there was an error that we're solving for the future updates of Shapash.
It should've been the raw dataset, before the preprocessing step, that should've been used like you've noticed.

About issue#2 :  
- We will add the different types that you've mentionned to allow add_input method to take more expected types and be less restrictives on the ypred parameter.

I'm opening a Pull Request to take your feedback in consideration and integrate them in Shapash. (You will be able to access it)
Don't hesitate if you have further comment. 

Thanks again for your feedbacks.

The Team Shapash.

**Comment by chetanambi** [comment]
It's working fine now. Thanks for putting the fix quickly!
