### ISSUE TITLE
Switch from SmartPredictor to SmartExplainer

### ISSUE THREAD

**Issue by chetanambi** [MAIF/shapash#111]
Hi Team,

Is it possible to generate local explanations on the new data added to SmartPredictor object? I went through all the tutorials and I understand that when we are satisfied with the explainability results given by Shapash, we can use the SmartPredictor object for deployment. But my question is how can we get local explanation chart after deployment on the new data that is coming in? I hope my question is clear. 

Thanks,
Chetan

**Comment by johannmartin** [comment]
Hello @chetanambi,

Thanks again for your feedbacks. Glad to see that you've taken the solution in hand. 

#To answer your question :
The local explanation chart is only available through the SmartExplainer Object for now. However, we just discussed about your question with the team. The need behind your question seems like a good idea. We are currently thinking about the best ways to integrate functionalities that will allow us to answer it. We will try to keep you informed about this.

 If you are interested, you can also contribute by forking this repository and follow the steps described in the contributing.md's file available in the repository

Thanks again for your contributions.

Hoping that this answer will suit you for now.

The Team Shapash.

**Comment by johannmartin** [comment]
**Description of Problem**:
In deployment, we are using the SmartPredictor object to get predictions and explainability of our models on specific datasets. The issue here is about the possibility to generate charts to visualize our results after deployment on this new data.

**Overview of the Solution**:
- add a new method on SmartPredictor object "to_smartexplainer" to switch from a SmartPredictor Object to a SmartExpxlainer one
  - Start with a check to ensure that the add_input step has been done with the SmartPredictor to get the specific data on which we want to analyse several charts 
  -  Initialize SmartExplainer Object with attributes from SmartPredictor
  - Compute the compile step of SmartExplainer with attributes and input used by the SmartPredictor for parameters

**Examples**:
![image](https://user-images.githubusercontent.com/61058807/109014731-b357d200-76b4-11eb-9718-0f4c71da6636.png)
![image](https://user-images.githubusercontent.com/61058807/109014779-bfdc2a80-76b4-11eb-9aa4-1c13ae8f9296.png)
![image](https://user-images.githubusercontent.com/61058807/109014909-e0a48000-76b4-11eb-9cac-c02c8b1cca41.png)
![image](https://user-images.githubusercontent.com/61058807/109015267-3d079f80-76b5-11eb-97ec-baa841ee099c.png)
![image](https://user-images.githubusercontent.com/61058807/109015492-74764c00-76b5-11eb-842d-4e5a9377bde9.png)
![image](https://user-images.githubusercontent.com/61058807/109015599-953ea180-76b5-11eb-8727-74961c207627.png)

**Comment by chetanambi** [comment]
@johannmartin When this feature will be available for use?

**Comment by johannmartin** [comment]
Hello @chetanambi,

We are currently working on a new release of Shapash and this method will be included. We've planned it for next week.
We'll keep you informed if there's any changes.

Thanks again for your contributions.

The Team Shapash.
