### ISSUE TITLE
Probability output

### ISSUE THREAD

**Issue by npapan69** [MAIF/shapash#153]
Dear all,
Many thanks for developing shapash, I have one question regarding the probability that is shown in the web app. Is it referring to the probability of the selected class or the probability of the positive class. If its the former, how someone can output the probability of the positive class.

Best regards
Nikos

**Comment by SebastienBidault** [comment]
Hello Nikos,

First of all, in the WebApp (top right) there is the "class to analyse" that is referring to the probabilities of the selected class.

When you say positive class, are you talking about predicted class ?
We haven't implemented the probabilities of the predicted class because it cannot work with the feature plot : 
- Can't show multiple predicted classes in the feature plot.
- There is a problem with having a predict proba scale and multiple modal.
By the way, mixing selected and predicted classes can cause some misunderstandings.

Otherwise, to_pandas() method can give the predicted value, the associated probability and local explainability.

**Comment by SebastienBidault** [comment]
I think you can use the "class to analyse".

Few example about how it works :

Class to analyse = 1, give probabilities to be positive for all rows.
Class to analyse = 0, give probabilities to be negative for all rows.

You can also use the filter row in the '_predict_' column of the dataset to do some focus.
Class to analyse = 1 & _predict_ = 0 , give probabilities to be positive only for predicted label = 0.
Class to analyse = 1 & _predict_ = 1 , give probabilities to be positive only for predicted label = 1.

Class to analyse = 0 & _predict_ = 0 , give probabilities to be negative only for predicted label = 0.
Class to analyse = 0 & _predict_ = 1 , give probabilities to be negative only for predicted label = 1.

Hope i'v understood well.

![image](https://user-images.githubusercontent.com/57792044/113322640-39e77b00-9315-11eb-9900-f32a999b310c.png)
