### ISSUE TITLE
why only notebook example? ?   I don't use notebook,  how can I show the chart?

### ISSUE THREAD

**Issue by RockLeeStudio** [MAIF/shapash#189]
why only notebook example? ? I don't use notebook, how can I show the chart? #189

**Comment by ThibaudReal** [comment]
Hello @RockLeeStudio 

We are using notebooks as it is an easy way to explore and show the possibilities of the Shapash library.
Even if you don’t use notebooks you can still open the tutorials using GitHub directly. Tutorials can be found here: https://github.com/MAIF/shapash/tree/master/tutorial.

If you want to use the plot methods in a script directly, you just need to add the `file_name` parameter in order to save the plot locally in a file. 
For example, instead of the following line that you can find in multiple tutorials : 
```
xpl.plot.features_importance()
```

You can use 
```
xpl.plot.features_importance(file_name=‘path_to_where_to_save_the_plot’)
```
Please refer to the documentation for a full description of the parameters : https://shapash.readthedocs.io/en/latest/


Also you can use the following script that is not in a notebook format and present an example of how to launch the web app using the house prices example : https://github.com/MAIF/shapash/blob/master/shapash/webapp/webapp_launch_DVF.py

We will also add an example script of how to generate the Shapash Report soon.

**Comment by RockLeeStudio** [comment]
Thanks for your reply.Very useful information.




--  
***@***.***
